student(dani,prolog).
student(nili,history).
student(nili,prolog).
student(ran,matimatics).
student(ran,prolog).
student(ran,history).
student(dani,matimatics).
parent(yair,hila).
parent(yair,dvir).
parent(lilach,hila).
parent(lilach,dvir).
parent(david,yair).
parent(ruti,yair).
parent(amos,lilach).
parent(nava,lilach).
male(david).
male(yair).
male(amos).
female(lilach).
female(ruti).
female(nava).
father(X,Y):-parent(X,Y),male(X).
mother(X,Y):-parent(X,Y),female(X).
married(yair,lilach).
married(X,Y):-parent(X,Z),parent(Y,Z),male(X),female(Y).
